apiVersion: v1
kind: ConfigMap
metadata:
  name: bashupload-config
  labels:
    app: bashupload
data:
  PHP_UPLOAD_MAX_FILESIZE: "2G"
  PHP_POST_MAX_SIZE: "2G"
  PHP_MAX_EXECUTION_TIME: "1800"
  PHP_MEMORY_LIMIT: "256M"
  SERVICE_NGINX_CLIENT_MAX_BODY_SIZE: "2G"
  WEB_DOCUMENT_ROOT: "/app/web"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bashupload-data
  labels:
    app: bashupload
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bashupload
  labels:
    app: bashupload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bashupload
  template:
    metadata:
      labels:
        app: bashupload
    spec:
      containers:
        - name: bashupload
          image: troke12/bashupload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: bashupload-config
          volumeMounts:
            - name: data
              mountPath: /var/files
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bashupload-data
---
apiVersion: v1
kind: Service
metadata:
  name: bashupload
  labels:
    app: bashupload
spec:
  type: ClusterIP
  selector:
    app: bashupload
  ports:
    - name: tcp-bashupload
      port: 80
      targetPort: 80